title: Garrek.org
description: >- # this means to ignore newlines until "baseurl:"
    Recepticle for ongoing brain dumps by Garrek Stemo
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://garrek.org"

twitter_username: GarrekStemo
github_username:  garrekstemo

# Build settings
plugins:
  - jekyll-feed

exclude:
  - _drafts/